
data_local: /s/project/semi_supervised_multispecies/all_fungi_reference/fungi/Annotation/Sequences/AAA_Concatenated/pretokenized/speciesdownstream300
data_remote: 

max_seq_len: 512
tokenizer_name: gagneurlab/SpeciesLM
mlm_probability: 0.02

# Run Name
run_name: droplast_wd_monarch-mixer-pretrain-786dim-80m-parameters

# Model
model:
  name: bert
  pretrained_model_name: bert-base-uncased
  tokenizer_name: ${tokenizer_name}
  model_config:
    num_attention_heads: 12 
    num_hidden_layers: 12 
    attention_probs_dropout_prob: 0.0 
    max_position_embeddings: ${max_seq_len}

    monarch_mixer_sequence_mixing: True
    long_conv_l_max: ${max_seq_len}
    long_conv_kernel_learning_rate: 1e-3
    hyena_lr_pos_emb: 1e-5
    hyena_w: 10
    hyena_wd: 0.1
    hyena_emb_dim: 5
    hyena_filter_order: 128

    bidirectional: true
    residual_long_conv: true

    use_glu_mlp: True
    use_monarch_mlp: True
    monarch_mlp_nblocks: 4
    use_positional_encodings: True
    
# Dataloaders
train_loader:
  name: dna
  dataset:
    local: ${data_local}
    remote: 
    split: train
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    shuffle: true
    mlm_probability: ${mlm_probability}
  drop_last: true
  num_workers: 8

eval_loader:
  name: dna
  dataset:
    local: ${data_local}
    remote: 
    split: test
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    shuffle: false
    mlm_probability: 0.02
  drop_last: false
  num_workers: 8

# Optimization
scheduler:
  name: linear_decay_with_warmup
  t_warmup: 0.1dur # Warmup to the full LR for 6% of the training duration
  alpha_f: 0.00 # Linearly decay to 0.02x the full LR by the end of the training duration

precision: fp32

optimizer:
  name: decoupled_adamw
  lr: 4.0e-4 # Peak learning rate
  betas:
  - 0.9
  - 0.98
  eps: 1.0e-06
  weight_decay: 0.01 # Amount of weight decay regularization

algorithms:
  gradient_clipping: {
    clipping_type: 'norm',
    clipping_threshold: 1.0
  }

max_duration: 100000ba # Subsample the training data for ~275M samples
eval_interval: 2000ba
global_train_batch_size: 2048

# System
seed: 17
device_eval_batch_size: 64
device_train_microbatch_size: 64
# device_train_microbatch_size: auto

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 1ba

callbacks:
  speed_monitor:
    window_size: 500
  lr_monitor: {}

loggers:
 wandb:
   project: dnam2    # Fill this in
   entity: luluh     # Fill this in


# Checkpoint
save_interval: 1000ba
save_num_checkpoints_to_keep: 10  
save_folder: ./local-bert-checkpoints/${run_name}   
